### ISSUE TITLE
shrinkwrap

### ISSUE THREAD

**Issue by jennschiffer** [bocoup/people#48]

**Comment by jugglinmike** [comment]
This issue is scant on the details, but it most likely describes npm's "shrinkwrap" command and file. In the years since it was opened, npm implemented a separate feature called "package lock" which is more suitable for our needs. Tyler added a lock file via [commit c29becf](https://github.com/bocoup/people/commit/c29becfd7f114a8c602ddd475e999345fbfe1601), so it's safe to consider this issue resolved.

**Comment by jennschiffer** [comment]
scant on details is generous lol. miss ya mike!
